name: Deploy to AWS Amplify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build main site
        run: npm run build

      - name: Configure AWS credentials
        env:
          AWS_CREDENTIALS: ${{ secrets.DEPLOY_TO_AWS_AMPLIFY }}
        run: |
          # Split the credentials into their components
          IFS=':' read -r ACCESS_KEY_ID SECRET_ACCESS_KEY AMPLIFY_APP_ID <<< "$AWS_CREDENTIALS"
          
          # Configure AWS CLI
          aws configure set aws_access_key_id "$ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$SECRET_ACCESS_KEY"
          aws configure set region us-east-1
          
          # Export environment variables for Amplify
          echo "AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY" >> $GITHUB_ENV
          echo "AMPLIFY_APP_ID=$AMPLIFY_APP_ID" >> $GITHUB_ENV 